# Generated by Django 3.2.9 on 2022-07-08 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, upload_to='avatar/%Y/%m/%d')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('about', models.TextField(default='No About ...')),
                ('gender', models.CharField(choices=[('', 'Select Gender'), ('male', 'male'), ('female', 'female')], max_length=30)),
                ('user_type', models.CharField(choices=[('', 'Select Gender'), ('admin', 'admin'), ('plot_owner', 'plot_owner'), ('clerk', 'clerk')], max_length=30)),
                ('twitter', models.CharField(max_length=3000)),
                ('facebook', models.CharField(max_length=3000)),
                ('website', models.CharField(max_length=3000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
