# Generated by Django 3.2.9 on 2022-07-05 16:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220705_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='secret_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
