# Generated by Django 3.2.9 on 2022-07-06 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_appointment_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='completed',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
