# Generated by Django 3.2.9 on 2022-07-08 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_appointment_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='completed',
        ),
    ]
